import ArgumentParser
import Foundation
import KakaoCore

struct SchemaCommand: ParsableCommand {
    static let configuration = CommandConfiguration(
        commandName: "schema",
        abstract: "Dump the database schema (for reverse engineering)"
    )

    enum Format: String, ExpressibleByArgument {
        case sql
        case markdown
    }

    @Option(name: .long, help: "Path to database file")
    var db: String?

    @Option(name: .long, help: "Database encryption key")
    var key: String?

    @Option(name: .long, help: "Output format: sql (default) or markdown")
    var format: Format = .sql

    @Option(name: [.customLong("output"), .customShort("o")], help: "Write to this file instead of stdout")
    var output: String?

    func run() throws {
        let reader = try openDatabase(dbPath: db, key: key)
        defer { reader.close() }

        let tables = try reader.schema()
        if tables.isEmpty {
            print("No tables found (database may be encrypted).")
            return
        }

        let rendered = render(tables: tables, format: format)
        if let output {
            try rendered.write(toFile: output, atomically: true, encoding: .utf8)
            FileHandle.standardError.write(Data("Wrote \(tables.count) tables to \(output)\n".utf8))
        } else {
            print(rendered, terminator: "")
        }
    }

    private func render(tables: [(name: String, sql: String)], format: Format) -> String {
        var out = ""
        switch format {
        case .sql:
            for table in tables {
                out += "-- \(table.name)\n"
                out += "\(table.sql);\n\n"
            }
        case .markdown:
            out += "# KakaoTalk Database Schema\n\n"
            out += "Generated by `kakaocli schema --format markdown`.\n\n"
            out += "## Tables (\(tables.count))\n\n"
            for table in tables {
                let anchor = table.name.lowercased()
                out += "- [`\(table.name)`](#\(anchor))\n"
            }
            out += "\n"
            for table in tables {
                out += "## \(table.name)\n\n"
                out += "```sql\n"
                out += "\(table.sql);\n"
                out += "```\n\n"
            }
        }
        return out
    }
}
